update resources. finalize release 0.2.

diff --git a/src/archlinuxARM-installer b/src/archlinuxARM-installer
--- a/src/archlinuxARM-installer
+++ b/src/archlinuxARM-installer
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+##### Notes for developers.
+##### 1. Because Bash doesn't support module import very well, I kept everything 
+##### under this one file.
+##### 2. To quickly jump around, search for these markers:
+##### - "### " indicates a code block that should have been an imported module.
+##### - "#### " indicates a submodule.
+#####
+
 
 ### Sessions init and arguments capture.
 # Very weird Bash structure here for getopts.  Keep as-is.  No touchy.
@@ -14,35 +22,55 @@ function _print_help_and_exit {
 `           ` -v      activate debug log (true/false)
 `           ` -d      path to ArchLinuxARM image directory
 `           ` -b      path to block device to be installed (/dev/sdX)
-`           ` -m      board model name"
+`           ` -m      board model name \n
+`           `Supported devices:
+`           ` notes: Device names are taken directly from their appropriate
+`           `ArchLinuxARM.org page, with dash \"-\" replaced by \
+`           `underscore \"_\".\n
+`           `a10_olinuxino_lime         clearfog      odroid_x
+`           `a20_olinuxino_lime         cubieboard    odroid_x2
+`           `a20_olinuxino_lime2        cubieboard_2  odroid_xu
+`           `a20_olinuxino_micro        cubietruck    odroid_xu3
+`           `beagleboard                cubox_i       odroid_xu4
+`           `beagleboard_xm             odroid_c1     pandaboard
+`           `beaglebone                 odroid_c2     pcduino3
+`           `beaglebone_black           odroid_hc1    raspberry_pi
+`           `beaglebone_black_wireless  odroid_hc2    raspberry_pi_2
+`           `beaglebone_green           odroid_u2     raspberry_pi_3
+`           `beaglebone_green_wireless  odroid_u3 \n"
     exit 2
 }
 
 
-while getopts "hvd:b:m:t:" opt; do
+while getopts "hl:d:b:m:" opt; do
     # "hvd:b:m:" is Bash majik. The following ": seems to means
     # that the parameter requires an argument.
-    case $opt in
+    case "${opt}" in
         h)
             _print_help_and_exit
             ;;
-        v)
-            debug_mode="True"
-            ;;
-        d)
-            img_path="${OPTARG}"
-            required_parameter_check[1]="d"
+        l)
+            case "${OPTARG}" in
+                "info"|"INFO"|"warning"|"WARNING"|\
+                "error"|"ERROR"|"debug"|"DEBUG")
+                    log_level="${OPTARG}"
+                    ;;
+                *)
+                    echo "Log level ${OPTARG} not recognized. Set to INFO."
+                    log_level="INFO"
+            esac
             ;;
         b)
             install_disk="${OPTARG}"
             required_parameter_check[0]="b"
             ;;
+        d)
+            img_path="${OPTARG}"
+            required_parameter_check[1]="d"
+            ;;
         m)
             board_model="${OPTARG}"
             required_parameter_check[2]="m"
-            ;;
-        t)
-            echo "testing ${OPTARG}"
             ;;
         \?)
             echo "Unsupported argument chosen: -${OPTARG}" >&2
@@ -53,10 +81,11 @@ done
 
 
 if [ "${required_parameter_check[*]}" != "b d m" ]; then
-    echo "All 3 parameters -b, -d, -m are required"
+    echo -e "All 3 parameters -b, -d, -m are required. \n"
     _print_help_and_exit
 fi
 
+`
 session_id=$(< /dev/urandom tr -dc 0-9 | head -c6)
 mount_path="/mnt/.alARM_install_${session_id}"
 ###
@@ -68,49 +97,72 @@ function current_timestamp {
 }
 
 
-function _logging {
+function logger {
     ## Take 2 positional arguments.
-    ## ${1} for loglevel: info, warning, error, debug
+    ## ${1} for loglevel: debug, info, warning, error
     ## ${2} for log messages
     ##
     ## ${1} ${2} MUST always be wrapped in double quotes.
-    ## Env variable ${debug_mode} is checked for debug log printing.
-    ## Loglevel ERROR will cause the program to exit.
-    case ${1} in
+    ## Logging event at level ERROR will cause the program to exit.
+    case "${log_level}" in
+        "debug"|"DEBUG")
+            log_level_num=10
+            ;;
         "info"|"INFO")
-            echo "[$(current_timestamp)] INFO: ${2}"
+            log_level_num=20
             ;;
         "warning"|"WARNING")
-            echo "[$(current_timestamp)] WARNING: ${2}"
+            log_level_num=30
             ;;
         "error"|"ERROR")
-            echo "[$(current_timestamp)] ERROR: ${2}"
-            exit 1
-            ;;
-        "debug"|"DEBUG")
-            case "${debug_mode}" in
-                "true"|"TRUE")
-                    echo "[$(current_timestamp)] DEBUG: ${2}"
-                    ;;
-                *)
-                    ;;
-            esac
+            log_level_num=40
             ;;
     esac
+
+    case "${1}" in
+        "debug"|"DEBUG")
+            if [ ${log_level_num} <= 10 ]; then
+                echo "[$(current_timestamp)] DEBUG: ${2}"
+            fi
+            ;;
+        "info"|"INFO")
+            if [ ${log_level_num} <= 20 ]; then
+                echo "[$(current_timestamp)] INFO: ${2}"
+            fi
+            ;;
+        "warning"|"WARNING")
+            if [ ${log_level_num} <= 30 ]; then
+                echo "[$(current_timestamp)] WARNING: ${2}"
+            fi
+            ;;
+        "error"|"ERROR")
+            if [ ${log_level_num} <= 40 ]; then
+                echo "[$(current_timestamp)] ERROR: ${2}"
+            fi
+            exit 1
+            ;;
+    esac
+}
+
+
+function logging_debug {
+    ## Take 1 positional argument.
+    ## ${1} for log message.
+    logger "DEBUG" ${1}
 }
 
 
 function logging_info {
     ## Take 1 positional argument.
     ## ${1} for log message.
-    _logging "INFO" "${1}"
+    logger "INFO" "${1}"
 }
 
 
 function logging_warning {
     ## Take 1 positional argument.
     ## ${1} for log message.
-    _logging "WARNING" ${1}
+    logger "WARNING" ${1}
 }
 
 
@@ -119,14 +171,7 @@ function logging_error {
     ## ${1} for log message.
     ##
     ## This function will cause the program to exit.
-    _logging "ERROR" ${1}
-}
-
-
-function logging_debug {
-    ## Take 1 positional argument.
-    ## ${1} for log message.
-    _logging "DEBUG" ${1}
+    logger "ERROR" ${1}
 }
 ###
 
@@ -135,8 +180,10 @@ function logging_debug {
 function download {
     ## Wrap wget for desired behaviours.
     ## Take 1 positional parameter.
-    ## ${1} for download URL
-    wget -q -xnH --cut-dirs=1 --show-progress --progress=bar ${1}
+    ## ${1} for download URL *suffix*.
+    url_prefix="http://os.archlinuxarm.org/os"
+    url="${url_prefix}/${1}"
+    wget -q -xnH --cut-dirs=1 --show-progress --progress=bar "${url}"
 }
 ###
 
@@ -157,6 +204,7 @@ function _dt_1p_secdefault_ext4 {
 
     mkfs.ext4 -F "${install_disk}1" > /dev/null 2>&1
     # mkfs.ext4 -F "${install_disk}1" -O ^metadata_csum,^64bit > /dev/null 2>&1
+    # why?
     mkdir -p "${mount_path}/root"
     mount "${install_disk}1" "${mount_path}/root"
     logging_info "Created filesystem & mounted ${1}1 to ${mount_path}/root"
@@ -260,31 +308,65 @@ function _dt_2p_sec63_vfat16_sec100M_ext4 {
 
 
 #### Post install template
-function _pit_cubieboard {
-    dd if="${img_path}/sunxi/boot/cubieboard/u-boot-sunxi-with-spl.bin" \
-        of="${install_disk}" bs=1024 seek=8 status=none
-    cp "${img_path}/sunxi/boot/cubieboard/boot.scr" "${mount_path}/root/boot/boot.scr"
-    logging_info "Set up bootloader for ${board_model}"
-    sync
-}
-
-function _pit_cubieboard2 {
-    dd if="${img_path}/sunxi/boot/cubieboard2/u-boot-sunxi-with-spl.bin" \
-        of="${install_disk}" bs=1024 seek=8 status=none
-    cp "${img_path}/sunxi/boot/cubieboard2/boot.scr" "${mount_path}/root/boot/boot.scr"
-    logging_info "Set up bootloader for ${board_model}"
-    sync
-}
-
-
-function _pit_xu4 {
-    sh ${mount_path}/root/boot/sd_fusing.sh "${install_disk}"
-    logging_info "Set up bootloader for ${board_model}"
-    sync
-}
-
-function _pit_rpi {
+function _pit_raspberry_pi {
     mv "${mount_path}/root/boot/*" "${mount_path}/boot/"
+    logging_info "Set up bootloader for ${board_model}"
+    sync
+}
+
+
+function _pit_armv7 {
+    dd if="${img_path}/sunxi/boot/${board_model}/u-boot-sunxi-with-spl.bin" \
+        of="${install_disk}" bs=1024 seek=8 status=none
+    cp "${img_path}/sunxi/boot/${board_model}/boot.scr" \
+        "${mount_path}/root/boot/boot.scr"
+    logging_info "Set up bootloader for ${board_model}"
+    sync
+}
+
+
+function _pit_odroid {
+    sh "${mount_path}"/root/boot/sd_fusing.sh "${install_disk}"
+    logging_info "Set up bootloader for ${board_model}"
+    sync
+}
+
+
+function _pit_cubox_i {
+    dd if="${mount_path}"/root/boot/SPL of=/dev/sdX bs=1K seek=1
+    dd if="${mount_path}"/root/boot/u-boot.img of=/dev/sdX bs=1K seek=69
+    logging_info "Set up bootloader for ${board_model}"
+    sync
+}
+
+
+function _pit_beagleboard {
+    mv "${mount_path}"/root/boot/* "${mount_path}/boot/"
+    cp "${img_path}"/omap/boot/beagleboard/MLO \
+       "${img_path}"/omap/boot/beagleboard/u-boot.img "${mount_path}/boot/"
+    echo "/dev/mmcblk0p1  /boot  vfat  defaults  0 0" >> /etc/fstab
+    logging_info "Set up bootloader for ${board_model}"
+    sync
+}
+
+
+function _pit_beaglebone {
+    dd if="${mount_path}"root/boot/MLO \
+        of="${install_disk}" count=1 seek=1 conv=notrunc bs=128k
+    dd if="${mount_path}"root/boot/u-boot.img \
+        of="${install_disk}" count=2 seek=1 conv=notrunc bs=384k
+    logging_info "Set up bootloader for ${board_model}"
+    sync
+}
+
+
+function _pit_pandaboard {
+    dd if="${img_path}"/omap/boot/pandaboard/MLO \
+        of="${install_disk}" count=1 seek=1 conv=notrunc bs=128k
+    dd if="${img_path}"/omap/boot/pandaboard/u-boot.img \
+        of="${install_disk}" count=2 seek=1 conv=notrunc bs=384k
+    cp "${img_path}/omap/boot/pandaboard/boot.scr" \
+        "${mount_path}/root/boot/boot.scr"
     logging_info "Set up bootloader for ${board_model}"
     sync
 }
@@ -298,43 +380,75 @@ function prepare_env {
         "raspberry_pi")
             export img_name="ArchLinuxARM-rpi-latest.tar.gz"
             export disk_template="2p_secdefault_vfat_sec100M_ext4"
+            export post_install_template="raspberry_pi"
             ;;
-        "cubieboard"|"cubieboard_2"|"cubietruck"|"pandaboard")
+        "a10_olinuxino_lime"|"a20_olinuxino_lime"|\
+        "a20_olinuxino_lime2"|"a20_olinuxino_micro"|\
+        "cubieboard"|"cubieboard_2"|"cubietruck"|"pcduino3")
             export img_name="ArchLinuxARM-armv7-latest.tar.gz"
             export disk_template="1p_sec2048_ext4"
+            export post_install_template="armv7"
             ;;
         "odroid_c1")
             export img_name="ArchLinuxARM-odroid-c1-latest.tar.gz"
             export disk_template="1p_secdefault_ext4"
+            export post_install_template="odroid"
             ;;
         "raspberry_pi_2"|"raspberry_pi_3")
             export img_name="ArchLinuxARM-rpi-2-latest.tar.gz"
             export disk_template="2p_secdefault_vfat_sec100M_ext4"
+            export post_install_template="raspberry_pi"
             ;;
         "cubox_i")
             export img_name="ArchLinuxARM-imx6-cubox-latest.tar.gz"
             export disk_template="1p_secdefault_ext4"
+            export post_install_template="cubox_i"
             ;;
         "clearfog")
             export img_name="ArchLinuxARM-clearfog-latest.tar.gz"
             export disk_template="1p_secdefault_ext4"
+            export post_install_template="odroid"
+            ;;
+        "odroid_u2"|"odroid_u3"|"odroid_x2")
+            export img_name="ArchLinuxARM-odroid-latest.tar.gz"
+            export disk_template="1p_sec4096_ext4"
+            export post_install_template="odroid"
+            ;;
+        "odroid_x")
+            export img_name="ArchLinuxARM-odroid-x-latest.tar.gz"
+            export disk_template="1p_sec4096_ext4"
+            export post_install_template="odroid"
             ;;
         "odroid_hc1"|"odroid_hc2"|"odroid_xu3"|"odroid_xu4")
             export img_name="ArchLinuxARM-odroid-xu3-latest.tar.gz"
             export disk_template="1p_sec4096_ext4"
+            export post_install_template="odroid"
+            ;;
+        "odroid_xu")
+            export img_name="ArchLinuxARM-odroid-xu3-latest.tar.gz"
+            export disk_template="1p_sec4096_ext4"
+            export post_install_template="raspberry_pi"
             ;;
         "beagleboard"|"beagleboard_xm")
             export img_name="ArchLinuxARM-armv7-latest.tar.gz"
             export disk_template="2p_sec63_vfat16_sec100M_ext4"
+            export post_install_template="beagleboard"
             ;;
         "beaglebone"|"beaglebone_black"|"beaglebone_black_wireless"|\
         "beaglebone_green"|"beaglebone_green_wireless")
             export img_name="ArchLinuxARM-am33x-latest.tar.gz"
             export disk_template="1p_sec2048_ext4"
+            export post_install_template="beaglebone"
             ;;
         "odroid_c2")
             export img_name="ArchLinuxARM-odroid-c2-latest.tar.gz"
             export disk_template="1p_secdefault_ext4"
+            export post_install_template="odroid"
+            ;;
+        "pandaboard")
+            export img_name="ArchLinuxARM-armv7-latest.tar.gz"
+            export disk_template="1p_sec2048_ext4"
+            export post_install_template="pandaboard"
             ;;
         *)
             logging_error "Board model ${board_model} not supported"
@@ -343,7 +457,7 @@ function prepare_env {
 }
 
 function post_install {
-    _pit_${board_model}
+    _pit_${post_install_template}
     # I know, I know, metaprogramming sucks.
 
     umount "${mount_path}/boot" > /dev/null 2>&1
@@ -355,7 +469,7 @@ function post_install {
 }
 
 function install {
-    logging_info "Extracting ${img} to ${mount_path}/root"
+    logging_debug "Extracting ${img} to ${mount_path}/root"
     bsdtar -xpf "${img}" -C "${mount_path}/root"
     logging_info "Extracted ${img} to ${mount_path}/root"
     sync
@@ -367,10 +481,10 @@ function format_disk {
     ##
     ## NOTE: This function requires sudo.
 
-    dd if=/dev/zero of=${install_disk} bs=1M count=8 status=none
+    dd if=/dev/zero of="${install_disk}" bs=1M count=8 status=none
     logging_info "Wiped out ${install_disk} with /dev/zero"
 
-    case ${disk_template} in
+    case "${disk_template}" in
         "1p_secdefault_ext4")
             _dt_1p_secdefault_ext4
             ;;
